### ISSUE TITLE
Issue with `dockq` Parameter Compatibility in Evaluation

### ISSUE THREAD

**Issue by BL-Lac149597870** [THUNLP-MT/PepGLAD#1]
Hi @kxz18 ,

I'm currently using your codes for evaluation purposes and have encountered an issue regarding the `dockq` parameter compatibility. It appears that some parameters utilized during the evaluation, such as `model_chain1` and `native_chain1`, are not supported in the latest version of `dockq`.

Could you please provide a version of `dockq` that is compatible with your project, or consider updating the code to align with the current specifications of `dockq`? I've attached a screenshot below for your reference.
<img width="710" alt="image" src="https://github.com/user-attachments/assets/17947ba8-d1e1-469b-a32c-54fc23ed01ad">

Thank you for your assistance and for the great work on this project!

Best regards

**Comment by kxz18** [comment]
Sorry for the mistake. Looks like the DockQ project has been updated to V2.0, while in this project we need V1.0. You can download V1.0 with `git clone --branch v1.0 --depth 1 https://github.com/bjornwallner/DockQ.git`. I have also updated the downloading command in `globals.py`.

Best regards

**Comment by BL-Lac149597870** [comment]
Thanks very much!
